spring:
  profile:
    active: dev
---
server:
  port: 7001 #注册中心占用7001端口,冒号后面必须要有空格
spring:
  profiles: dev
  application:
    name: lingluocloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001 #注册中心占用7001端口,冒号后面必须要有空格
spring:
  profiles: test
  application:
    name: lingluocloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/